name: my_fitness_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  flutter_echarts: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.4
  hive_generator: ^1.1.1

flutter:
  uses-material-design: true
