// class Record {
//   String title;
//   String? description; // Optional
//   DateTime dateOfEntry;
//   int calories;

//   Record({
//     required this.title,
//     required this.calories,
//     this.description,
//     required this.dateOfEntry,
//   });

//   Map<String, dynamic> toMap() {
//     return {
//       'title': title,
//       'description': description,
//       'dateOfEntry': dateOfEntry.toIso8601String(),
//       'calories': calories,
//     };
//   }

//   factory Record.fromMap(Map<String, dynamic> map) {
//     return Record(
//       title: map['title'],
//       description: map['description'],
//       dateOfEntry: DateTime.parse(map['dateOfEntry']),
//       calories: map['calories'],
//     );
//   }
// }
import 'package:hive/hive.dart';
part 'record.g.dart'; // The file generated by Hive

@HiveType(typeId: 0)
class Record extends HiveObject {
  @HiveField(0)
  String title;

  @HiveField(1)
  String? description;

  @HiveField(2)
  DateTime dateOfEntry;

  @HiveField(3)
  int calories;

  Record(
      {required this.title,
      this.description,
      required this.dateOfEntry,
      required this.calories});

  // toJson and fromJson methods
  // Convert a Record object into a map.

  // Map<String, dynamic> toJson() {
  //   return {
  //     'title': title,
  //     'description': description,
  //     'dateOfEntry':
  //         dateOfEntry.toIso8601String(), // Converting DateTime to String
  //     'calories': calories,
  //   };
  // }

  // Convert a map into a Record object.
  // static Record fromJson(Map<String, dynamic> json) {
  //   return Record(
  //     title: json['title'] as String,
  //     description: json['description'] as String?,
  //     dateOfEntry:
  //         DateTime.parse(json['dateOfEntry']), // Converting String to DateTime
  //     calories: json['calories'] as int,
  //   );
  // }
}
