// class Record {
//   String title;
//   String? description; // Optional
//   DateTime dateOfEntry;
//   int calories;

//   Record({
//     required this.title,
//     required this.calories,
//     this.description,
//     required this.dateOfEntry,
//   });

//   Map<String, dynamic> toMap() {
//     return {
//       'title': title,
//       'description': description,
//       'dateOfEntry': dateOfEntry.toIso8601String(),
//       'calories': calories,
//     };
//   }

//   factory Record.fromMap(Map<String, dynamic> map) {
//     return Record(
//       title: map['title'],
//       description: map['description'],
//       dateOfEntry: DateTime.parse(map['dateOfEntry']),
//       calories: map['calories'],
//     );
//   }
// }
import 'package:hive/hive.dart';

part 'record.g.dart'; // The file generated by Hive

@HiveType(typeId: 0)
class Record {
  @HiveField(0)
  final String title;

  @HiveField(1)
  final String? description;

  @HiveField(2)
  final DateTime dateOfEntry;

  @HiveField(3)
  final int calories;

  Record(
      {required this.title,
      this.description,
      required this.dateOfEntry,
      required this.calories});
}
